kind: Deployment ## Type de l'objet
apiVersion: apps/v1 # faux 1.18.0
metadata:
  name: nginx-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nginx
      version: latest
  template:
    metadata:
      labels:
        app: nginx
        version: latest
    spec:
      containers:
        - name: nginx
          image: nginx:latest
          ports:
            - containerPort: 80
