apiVersion: v1
kind: Pod
metadata:
  labels:
    app: web
  name: pod-blue
  namespace: production
spec:
  containers:
  - name: simple-webapp-color-blue
    image: mmumshad/simple-webapp-color
    ports:
    - containerPort: 80
    env:
    - name: APP_COLOR
      value: blue

